### ISSUE TITLE
Websocket Communication

### ISSUE THREAD

**Issue by ThatsTheEnd** [ThatsTheEnd/horiba-python-sdk#2]
## 🚀 Feature Request

Implement websocket communication with ICL

## 🔈 Tasks

- [ ] Websocket Communication Layer 
- [ ] Websocket Security
- [ ] Websocket Error Handling
- [ ] Websocket Testing & CI Integration
